### ISSUE TITLE
Automate GitHub policies

### ISSUE THREAD

**Issue by IlanZuckerman** [beyond-io/beyond#156]
For example: block merging to master if CI fails.

**Comment by lioramilbaum** [comment]
The request is to automate and validate the GitHub policies are set correctly with no drift. Ansible might be a suitable solution in case there is a github module.

**Comment by IlanZuckerman** [comment]
From vast looking at [GitHub modules](https://docs.ansible.com/ansible/latest/modules/list_of_source_control_modules.html) i found only those.
Neither of them feels like what we need for this purpose.

git_config – Read and write git configuration
github_deploy_key – Manages deploy keys for GitHub repositories
github_hooks – Manages GitHub service hooks (D)
github_issue – View GitHub issue
github_key – Manage GitHub access keys
github_release – Interact with GitHub Releases
github_webhook – Manage GitHub webhooks
github_webhook_info – Query information about GitHub webhooks

**Comment by lioramilbaum** [comment]
We have few options to consider:
- Look for other tools/services for GitOps
- Look for GitHub API for the manual settings we have performed and use a module which sends api requests
- Implement an Ansible module which does that
