### ISSUE TITLE
Add content to html Home page

### ISSUE THREAD

**Issue by IlanZuckerman** [beyond-io/beyond#161]
The content should be sufficient in order to understand the purpose of the site, what it does, why do we need it and so on.
At this page, no need to add specific labels to the buttons. Just add sufficient amount of content to the landing page. 

Acceptance Criteria:
- Home page content is relevant to the initiative purpose

**Comment by lioramilbaum** [comment]
@IlanZuckerman Would you mind adding Acceptance Criteria in the issue description?

**Comment by rliberma** [comment]
Working on the draft version we talked about + adding the main page links and remove all the housmade legacy content (-:

**Comment by lioramilbaum** [comment]
@rliberma I can't find a PR. Was it merged already or you haven't submitted it yet?
