### ISSUE TITLE
Change the Web Server port 5000 to port 80

### ISSUE THREAD

**Issue by rliberma** [beyond-io/beyond#167]
To be able to run our Web server on standard WWW port we are changing the code to support port 80 instead of port 5000. 

The following files needs to be modified:

bootstrap-infra.py:            'FromPort': 5000,
bootstrap-infra.py:            'ToPort': 5000,
tests/test_sanity.py:    response = requests.get("http://localhost:5000")
tests/functional/test_title.py:    selenium.get('http://localhost:5000')
tests/http_get_test.sh:if [ $(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:5000) = $exp_response ]; then
Vagrantfile:    dev.vm.network "forwarded_port", guest: 5000, host: 5000

Acceptance Criteria
- Application is running on port 80 and pass testing

**Comment by lioramilbaum** [comment]
Can you provide the reasoning why the port should be changed?

**Comment by rliberma** [comment]
This is following for what we have agreed in our yesterday meeting to change the Web server port to standard port 80 instead of port 5000. I need some more time to debug why this is failing in the prod instance test.

**Comment by lioramilbaum** [comment]
I remember we discussed that. We didn't discuss why port 80 is preferred. Can you dig the information and add it to the issue description?

**Comment by rliberma** [comment]
As agreed in our last meeting. We are keeping port 5000 at this point and i canceling this issue.
