### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by IlanZuckerman** [beyond-io/beyond#176]
Create Dockerfile in the projects root folder

On the image (installed with the Docker file) we should have:
- Ubunto distro
- Python3 Installed 
- Give the image a name: "beyond/app"

Acceptance Criteria:
Dockerfile exists

**Comment by rliberma** [comment]
@IlanZuckerman So it's pretty easy to do it with Docker hub image. And i did find an image for Ununtu and Python3 (https://hub.docker.com/r/fnndsc/ubuntu-python3) but i am not yet familiar enough with quay and not really understand the benefit for using it over Docker hub which is much simple. I need to understand first the benfit using quay over Docker hub and to learn more how to make Dockerfile running image from quay.io. I will glad to talk about it more in our next meeting before pushing any new lines.

**Comment by IlanZuckerman** [comment]
Roi, here is some info that will get you going:

The reason why we want to use quay.io repo instead of regular docker repo for pulling  base image, is because the docker hub has now a quota limiting anonymous users (thats who we are) to make more than 100 requests per 6 hours.

In quay.io repo we dont have this limitation, and you can also login to it with your redhat account!

In order to pull the image from it, you need to create the following line in Dockerfile:
`FROM quay.io/baselibrary/ubuntu:latest`

This will pull to your local PC or Vagrant VM (depends where from u will execute the command to build it 'docker build .') a latest ubuntu image.
the Image is already coming with Python 3.4.3 pre-installed, so you dont have to worry about it. 
You can check it by executing the following commands once you have the image:
`docker run -it <image> /bin/bash`

Also ,add this line to your DockerFile in order to update the packages when we will build the image:
`RUN apt-get update`

When all of this done, build the image and run it (just to make sure all is working), and make a commit with your Docker file.
No need to add to commit anything that has to do with actually building the image or running the container out of it (we other other tickets for that).

Hope all is clear. if not, pls ask in GChat.
