### ISSUE TITLE
Build an image out of DockerFile with 'docker build' and run it

### ISSUE THREAD

**Issue by IlanZuckerman** [beyond-io/beyond#179]
After having a DockerFile #176 , we wish to make an image out of it.

- Think (or lets discuss) where is the appropriate place in our code ('bootstrap.sh' ?) to put the build command.
- Add to appropriate place in a code, a command to build an image using the existing Dockerfile and run the container of of it.
- Add a test to tests/test_sanity.py checking that the image exists.

Acceptance Criteria:
- When deploying, an image is available and the container is up and running

**Comment by lioramilbaum** [comment]
Why the image build should take place in bootstrap.sh?
I would suggest that we only describe what the required implementation solves. Not how it is implemented.

**Comment by IlanZuckerman** [comment]
> Why the image build should take place in bootstrap.sh?
> I would suggest that we only describe what the required implementation solves. Not how it is implemented.

Thanks, i edited the description.
