### ISSUE TITLE
prod environment validation - Cloudwatch

### ISSUE THREAD

**Issue by lioramilbaum** [beyond-io/beyond#181]
Accessing the following endpoint returns 200
http://beyond-io.me.uk:5000

Two options:

GitHub Actions - schedule a workflow
AWS CloudWatch - Free tear

Acceptance Criteria:
Once a day a prod environment test is enabled

**Comment by rliberma** [comment]
Looks like we can start with the free version for testing.

Amazon CloudWatch pricing:
https://aws.amazon.com/cloudwatch/pricing/#:~:text=You%20can%20get%20started%20with,within%20these%20free%20tier%20limits.

**Comment by lioramilbaum** [comment]
> Looks like we can start with the free version for testing.
> 
> Amazon CloudWatch pricing:
> https://aws.amazon.com/cloudwatch/pricing/#:~:text=You%20can%20get%20started%20with,within%20these%20free%20tier%20limits.

Perfect. Can you set it up and demo the configuration on the coming sync meeting?

**Comment by ipolonsk** [comment]
I would love to help if needed, I did a small research on the topic yesterday (:

**Comment by rliberma** [comment]
AWS CloudWatch is configured. 
Should we change the configuration to AWS API in this issue or create a new one later?

**Comment by lioramilbaum** [comment]
Per our discussion earlier today, this issue can be closed.
@rliberma Please file a new issue for implementing the automation.

**Comment by rliberma** [comment]
The team agreed that we are good. Work for this issue has complated.
