### ISSUE TITLE
Make env vars, instead of hardcoding them repeatedly in different places

### ISSUE THREAD

**Issue by IlanZuckerman** [beyond-io/beyond#189]
Have the following vars defined somewhere in ONE place instead of keeping them redefined each time.
Store them somewhere appropriate for env vars (i think that we need to store them in .bash_profile).
See if there additional vars that needs to be extracted to env vars.

docker_runner.sh and bootstrap.sh
```
if [ "$HOME" = "/home/runner" ]; then
  my_path="."
else
  my_path="/vagrant"
fi
```

test_sanity.py 
WEB_APP_CONTAINER_NAME

**Comment by lioramilbaum** [comment]
Which env vars are you referring to?

**Comment by IlanZuckerman** [comment]
> Which env vars are you referring to?

As in example above:

my_path
WEB_APP_CONTAINER_NAME

**Comment by lioramilbaum** [comment]
I don't think we should store those in .bash_profile. Where is docker_runner.sh triggered?

**Comment by IlanZuckerman** [comment]
> I don't think we should store those in .bash_profile. Where is docker_runner.sh triggered?

If my branch 'docker_image_run' will be merged as is, then docker_runner.sh  is being invoked from:
Vagrant
and
main.yml   of the github flow

**Comment by lioramilbaum** [comment]
Than, let's discuss this issue over your PR. This doesn't sound like the right approach.

**Comment by IlanZuckerman** [comment]
> Than, let's discuss this issue over your PR. This doesn't sound like the right approach.

Lets discuss this on Sunday. :)

**Comment by IlanZuckerman** [comment]
On last meeting (10.1) we said that we would re-open this if we encounter this issue again where the same var is re-defined in different places of the code.

**Comment by IlanZuckerman** [comment]
On last meeting (10.1) we said that we would re-open this if we encounter this issue again where the same var is re-defined in different places of the code.
