### ISSUE TITLE
prevent from syncing file nohup.out to the sever on deployment

### ISSUE THREAD

**Issue by ipolonsk** [beyond-io/beyond#191]
Our application uses nohup as a way to redirect the python output to a file, the file name is nohup.out.
we would like this file to be created on run during the bootstrap process, we need to tell vagrant  not to copy the file from our local folder to the server during the vagrant up command (by default everything from the local folder is copied to the server under /vagrant folder)

**Comment by lioramilbaum** [comment]
I am not sure it is possible to configure vagrant to copy a subset of the files.  There are other options to deal with it. For example, use a unique log name or removing the file before starting the process.

**Comment by ipolonsk** [comment]
We are using right now an option to exclude files from the rsync process, using this syntax: 
config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [ "venv/", ".git/", ".idea/" ]
so as I see it we need to add another parameter (the name of the file -nohup.out) and this way we will make sure that we don't have this file on the server before the app deployment.

**Comment by lioramilbaum** [comment]
Right. Forgot the exclude option exists.

**Comment by ipolonsk** [comment]
We need to rewrite the nohup redirection to a specific file name we define and not to use the default(nohup.out), this will make this issue unneeded.
