### ISSUE TITLE
Find ssh connection method to give the ability for everybody to ssh to the VM.

### ISSUE THREAD

**Issue by ipolonsk** [beyond-io/beyond#194]
We are missing the option of ssh into the VM from each project member computer. 
Right now, only the member who created the VM (production deployment at AWS) can ssh into the VM because Vagrant copies only his public key to the new VM.
Few options on how to achieve it:
a. Find out if Vagrant can copy multiple keys using the AWS plugin.
b. Create a file that will hold all of our keys in it, and during the bootstrap, copy this file to /user/ubuntu/.ssh/authorized_keys.
c. FInd out if AWS gives an automatic option for each new VM created to have those X keys deployed on the VM.

**Comment by lioramilbaum** [comment]
AWS userdata feature can be very helpful for this use case

**Comment by ipolonsk** [comment]
In our case we are implementing the AWS user-data ourselves with the bootstrap.sh/bootstrap-infra.sh (both answering the definition of: "perform common automated configuration tasks and even run scripts after the instance starts"). 
From what I read about vagrant's AWS plugin it is not working with optional value for the user-date.
I think we need to implement the copy of the keys file to /user/ubuntu/.ssh/authorized_keys in the bootstrap.sh.
