### ISSUE TITLE
Add Github actions notification for the scheduled workflow

### ISSUE THREAD

**Issue by ipolonsk** [beyond-io/beyond#195]
In Github actions workflows runs are triggered by the committer, and because only one person has committed the changes of this workflow(Ilana), only this person gets notifications if the scheduled run failed.
We need to find a way to notify every member about a failure in the scheduled run.
One option to do it is with a marketplace plugin for GitHub action to add to the workflow.

**Comment by ipolonsk** [comment]
I read about Marketplace actions that we can use to notify everyone on a failed scheduled workflow, most of them request a to enter(in secure way) details about your gmaill account in order to user SMTP servers of Google, or set up a email server/service via AWS. 

References:
- https://github.com/racket/email-notifications
- https://dev.to/ravsamhq/send-an-email-notification-when-github-actions-fails-19i9

**Comment by lioramilbaum** [comment]
We can use that until @rliberma figures out if cloudwatch is a valid solution in terms of notification configuration and costs.

**Comment by ipolonsk** [comment]
We switched to cloudwatch on the AWS, so we can close this issue.
