### ISSUE TITLE
Provision the Docker container via Docker file

### ISSUE THREAD

**Issue by IlanZuckerman** [beyond-io/beyond#199]
Now when we have an empty up and running docker container, we should start provision it with all the needed code + dependencies to run the web app. 
Currently, the bootstrap.sh does that.
Make use of Docker file in order to build an image with all that.

UPDATE: this should all work only on DEV env (Vagrant VM) at this stage.

**Comment by lioramilbaum** [comment]
We can disable the execution of the application on the guest VM as soon as the container running on that guest is executing the application successfully.
