### ISSUE TITLE
Create our own namespace / domain / repo on quay.io

### ISSUE THREAD

**Issue by IlanZuckerman** [beyond-io/beyond#212]
Investigate the quay.io repo and see what needs to be done in order to properly use it for pushing (and pulling) our image on it.

**Comment by lioramilbaum** [comment]
Acceptance Criteria is missing

**Comment by IlanZuckerman** [comment]
I created organization + namespace in quay:
https://quay.io/repository/beyond-io/beyond

I think that next step should be linking it to our 'beyond-io' git hub repo, right?
I dont have the permissions to do that, I think @lioramilbaum owns it...

**Comment by IlanZuckerman** [comment]
Currently the name space is 'beyond-io'.
From tthe setting menu i can see that:
"Organization names cannot currently be changed"
So I will re-create the name space and repo, and name it as follows:
namespace: redhat-beyond 
repo: beyond.
Is that fine in sense of naming?

**Comment by IlanZuckerman** [comment]
Name Space create with a public repo:
https://quay.io/repository/redhat-beyond/beyond
