### ISSUE TITLE
Show 'cycles' information via tab

### ISSUE THREAD

**Issue by IlanZuckerman** [beyond-io/beyond#214]
The new web page needs to be below 'cycles' tab.
@lioramilbaum please share here the content of this 'cycles' presentation that you showed us today (21.2.21)

acceptance criteria:
'Cycles' tab added
'Cycles' tab has some basic content in it
Webdriver test added for the new page

**Comment by lioramilbaum** [comment]
https://docs.google.com/presentation/d/1f5yx7yMDuaualOglxUvlYHF2hkHYXh51TXT-Gv9VXYU
