### ISSUE TITLE
Investigate which DB will be most appropriate for our needs

### ISSUE THREAD

**Issue by IlanZuckerman** [beyond-io/beyond#215]
Casandra / postgres / MySQL or any other

**Comment by lioramilbaum** [comment]
Acceptance Criteria is missing

**Comment by IlanZuckerman** [comment]
MariaDB would be perfect match for us, as it is open source and can be easily connected with flask, and it has [official docker image](https://hub.docker.com/_/mariadb), and it will remain free under the GNU GPL

**Comment by lioramilbaum** [comment]
What about the other options?

**Comment by IlanZuckerman** [comment]
I compared some of the other alternatives (MySQL, postgres and some more). MiraDB is most suitable for our needs.
But really, the differences are not that big (for our small web app).
The major point for a decisions is that MariaDB is free forever and open source.

**Comment by lioramilbaum** [comment]
> I compared some of the other alternatives (MySQL, postgres and some more). MiraDB is most suitable for our needs.
> But really, the differences are not that big (for our small web app).
> The major point for a decisions is that MariaDB is free forever and open source.

Have we talked about the criteria for choosing one solution over another?

**Comment by IlanZuckerman** [comment]
We decided to proceed with postgres DB. that patch was already merged, so closing this.
