### ISSUE TITLE
Install the chosen DB type on a new container

### ISSUE THREAD

**Issue by IlanZuckerman** [beyond-io/beyond#216]
**Bear in mind the following:**
- Appropriate Base docker container Should be used to run the DB. Investigate the existing containers on the docker repo.
- Make the needed dependencies installations (apt-get install or whatever)
- If unique user needs to be created, then create it
- Make the needed arrangements for password and auth for our DB.
- Create a basic schema / DB for our needs. No need to populate it with data just yet.

acceptance criteria:

- DB is running in a separate docker container
- DB container and web app can communicate
- Test added to check whether the DB container is up and running

**Comment by lioramilbaum** [comment]
@IlanZuckerman Can you please add acceptance criteria?
