### ISSUE TITLE
Household flask app - write user story

### ISSUE THREAD

**Issue by IlanZuckerman** [beyond-io/beyond#70]
I'm on it

**Comment by IlanZuckerman** [comment]
As an employer of housemaid, I want to be able to manage her working hours and take care of her social rights as an employee.

This goal should be achieved by designing and implementing a web application that will track the following:
1. Keep records of all of the housemaids. including heir first and last names, date of birth, social security ID.
2. Working hours per each day for each housemaid.
3. Track the amount of available vacation and sick days per housemaid.
4. Each month make a salary report.

**Comment by lioramilbaum** [comment]
@IlanZuckerman Can you break down this story into tasks?

**Comment by IlanZuckerman** [comment]
> @IlanZuckerman Can you break down this story into tasks?

YEs, i edited the story.

**Comment by lioramilbaum** [comment]
@IlanZuckerman Can you please file an issue for the first task in the list?

**Comment by IlanZuckerman** [comment]
@lioramilbaum you mean the "Implement MariaDB" ?
